# Generated by Django 5.0.3 on 2024-03-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default=912, max_length=3, verbose_name='Код телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Номер телефона'),
        ),
    ]
