# Generated by Django 5.0.3 on 2024-03-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_code_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, max_length=7, verbose_name='Номер телефона'),
        ),
    ]
