# Generated by Django 5.0.3 on 2024-03-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='XXX', max_length=3, verbose_name='Код телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='XXXXXXX', max_length=7, verbose_name='Номер телефона'),
        ),
    ]
