# Generated by Django 5.0.3 on 2024-03-14 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_network', '0003_contact_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contacts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronic_network.contact', verbose_name='Контактная информация'),
        ),
    ]
